//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallowUP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGES
    {
        public int MESSAGEID { get; set; }
        public int FROMID { get; set; }
        public int TOID { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<System.TimeSpan> TIME { get; set; }
        public bool ACTIVE { get; set; }
        public string TITLE { get; set; }
        public string FROMNAME { get; set; }
        public string FROMSURNAME { get; set; }
        public string FROMMAIL { get; set; }
    
        public virtual USERS USERS { get; set; }
        public virtual USERS USERS1 { get; set; }
    }
}
