//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallowUP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTES
    {
        public int NOTEID { get; set; }
        public int STUDENTID { get; set; }
        public int NOTE { get; set; }
        public int CLASSID { get; set; }
        public int TEACHERID { get; set; }
        public bool ACTIVE { get; set; }
    
        public virtual TEACHERCLASS TEACHERCLASS { get; set; }
        public virtual USERS USERS { get; set; }
        public virtual USERS USERS1 { get; set; }
    }
}
