//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallowUP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENTCLASS
    {
        public int STUDENTID { get; set; }
        public int CLASSID { get; set; }
        public string CLASSNAME { get; set; }
        public string CLASSPASSWORD { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public int ID { get; set; }
    
        public virtual TEACHERCLASS TEACHERCLASS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
