//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallowUP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENTHOMEWORK
    {
        public int ID { get; set; }
        public int STUDENTID { get; set; }
        public Nullable<int> HOMEWORKID { get; set; }
        public Nullable<int> TEACHERID { get; set; }
        public string TEACHERNAME { get; set; }
        public string TEACHERSURNAME { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.TimeSpan> STARTTIME { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<System.TimeSpan> ENDTIME { get; set; }
        public Nullable<int> NOTE { get; set; }
        public string HOMEWORK { get; set; }
        public string HOMEWORKNAME { get; set; }
        public string STUDENTNAME { get; set; }
        public string STUDENTSURNAME { get; set; }
        public string CLASSNAME { get; set; }
        public Nullable<int> CLASSID { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public string UPLOAD { get; set; }
    
        public virtual HOMEWORK HOMEWORK1 { get; set; }
        public virtual USERS USERS { get; set; }
        public virtual USERS USERS1 { get; set; }
    }
}
