//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FallowUP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHERCLASS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEACHERCLASS()
        {
            this.HOMEWORK = new HashSet<HOMEWORK>();
            this.NOTES = new HashSet<NOTES>();
            this.STUDENTCLASS = new HashSet<STUDENTCLASS>();
        }
    
        public int CLASSID { get; set; }
        public string NAME { get; set; }
        public string PASSWORD { get; set; }
        public int TEACHERID { get; set; }
        public bool ACTIVE { get; set; }
        public string TEACHERNAME { get; set; }
        public string TEACHERSURNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOMEWORK> HOMEWORK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTES> NOTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENTCLASS> STUDENTCLASS { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
